# Generated by Django 4.2.30 on 2026-06-29 02:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecenas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mecenas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MecenasInscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_comprometido', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecenas', to='inscripciones.inscripcion')),
                ('mecenas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_patrocinadas', to='mecenas.mecenas')),
            ],
            options={
                'verbose_name': 'Mecenas Inscripcion',
                'ordering': ['-created_at'],
                'unique_together': {('mecenas', 'inscripcion')},
            },
        ),
    ]
