# Generated by Django 4.2.30 on 2026-06-29 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_preferido', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('ambos', 'Email y Push'), ('ninguno', 'Ninguno')], default='email', max_length=10)),
                ('horario_inicio', models.TimeField(default='08:00')),
                ('horario_fin', models.TimeField(default='21:00')),
                ('max_por_dia', models.PositiveIntegerField(default=5)),
                ('recibir_recordatorios', models.BooleanField(default=True)),
                ('recibir_comunicados', models.BooleanField(default=True)),
                ('recibir_alertas_docs', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de Notificacion',
            },
        ),
    ]
