# Generated by Django 4.2.30 on 2026-06-28 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viajes', '0004_alumno_alumno_unique_documento_por_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='viajes.cuota')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='inscripciones.inscripcion')),
                ('pagado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(('importe__gt', 0)), name='pago_importe_positivo'),
        ),
    ]
