# Generated by Django 4.2.30 on 2026-06-28 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0004_alumno_alumno_unique_documento_por_agencia'),
        ('autenticacion', '0002_padretutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=20)),
                ('num_pasaporte', models.CharField(blank=True, max_length=30)),
                ('necesidades_especiales', models.TextField(blank=True)),
                ('nombre_tutor_legal', models.CharField(max_length=200)),
                ('telefono_emergencia', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_inscritos', to='viajes.grupo')),
                ('tutores', models.ManyToManyField(blank=True, related_name='alumnos', to='autenticacion.padretutor')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumno',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('baja', 'Baja')], default='pendiente', max_length=20)),
                ('notas_internas', models.TextField(blank=True)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='inscripciones.alumno')),
                ('padre_tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='autenticacion.padretutor')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'indexes': [models.Index(fields=['viaje', 'estado'], name='inscripcion_viaje_i_7df9eb_idx'), models.Index(fields=['padre_tutor'], name='inscripcion_padre_t_23564e_idx')],
                'unique_together': {('alumno', 'viaje')},
            },
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['dni'], name='inscripcion_dni_396195_idx'),
        ),
    ]
