# Generated by Django 4.2.30 on 2026-06-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alergeno_altramuces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_apio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_cacahuetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_crustaceos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_frutos_cascara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_huevos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_lacteos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_moluscos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_mostaza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_pescado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_sesamo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_soja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergeno_sulfitos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='colegio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_altramuces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_apio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_cacahuetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_crustaceos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_frutos_cascara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_huevos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_lacteos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_moluscos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_mostaza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_pescado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_sesamo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_soja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alergeno_sulfitos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='colegio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
