# Generated by Django 4.2.30 on 2026-06-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_etapaitinerario_codigo_etapaitinerario_slug_and_more'),
        ('inscripciones', '0002_alumno_alergeno_altramuces_alumno_alergeno_apio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='hotel_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones', to='viajes.hotel'),
        ),
    ]
