# Generated by Django 4.2.30 on 2026-06-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_inscripcion_hotel_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='acceso_alumno_habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
