# Generated by Django 4.2.30 on 2026-06-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modular', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=300)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('gestion', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Colegio',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['departamento', 'nombre'], name='colegios_co_departa_c76f7e_idx')],
            },
        ),
    ]
