# Generated by Django 4.2.30 on 2026-06-29 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viajes', '0004_alumno_alumno_unique_documento_por_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('cuerpo', models.TextField()),
                ('enviado_email', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_enviados', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
