# Generated by Django 4.2.30 on 2026-06-28 04:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre comercial')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agencias/logos/', verbose_name='Logo')),
                ('email_contacto', models.EmailField(max_length=254, unique=True, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('licencia_agencia', models.CharField(blank=True, max_length=100, verbose_name='Nº licencia oficial')),
                ('slug', models.SlugField(help_text='Identificador único en URL. Ejemplo: totem', max_length=100, unique=True, verbose_name='Slug (identificador URL)')),
                ('activa', models.BooleanField(default=True, help_text='Desactivar para suspender el acceso del tenant sin eliminar datos.', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'ordering': ['nombre'],
            },
        ),
    ]
