# Generated by Django 4.2.30 on 2026-06-29 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0004_alumno_alumno_unique_documento_por_agencia'),
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEntregado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('documento_requerido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='viajes.documentorequerido')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inscripciones.inscripcion')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Entregado',
                'indexes': [models.Index(fields=['inscripcion', 'estado'], name='documentos__inscrip_918bf7_idx'), models.Index(fields=['documento_requerido', 'estado'], name='documentos__documen_d12eb9_idx')],
            },
        ),
    ]
