# Generated by Django 4.2.30 on 2026-06-28 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('destino', models.CharField(max_length=200)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='viajes/portadas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='agencias.agencia')),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('total_cuotas', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pago', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cuota', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('plan_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='viajes.planpago')),
            ],
            options={
                'ordering': ['numero_cuota'],
            },
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['agencia', 'estado'], name='viajes_viaj_agencia_a06b70_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['fecha_salida'], name='viajes_viaj_fecha_s_e18c18_idx'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.CheckConstraint(check=models.Q(('fecha_regreso__gt', models.F('fecha_salida'))), name='viaje_fecha_regreso_mayor_salida', violation_error_message='La fecha de regreso debe ser posterior a la fecha de salida.'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(check=models.Q(('importe__gt', 0)), name='cuota_importe_positivo', violation_error_message='El importe de la cuota debe ser mayor que 0.'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('plan_pago', 'numero_cuota'), name='unique_cuota_por_plan'),
        ),
    ]
