# Generated by Django 4.2.30 on 2026-06-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje_slug_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaitinerario',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='etapaitinerario',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(blank=True, choices=[('vuelo', 'Vuelo / Traslado aÃ©reo'), ('bus', 'Transporte terrestre'), ('hotel', 'Alojamiento / Check-in'), ('comida', 'Comidas (Desayuno, Almuerzo, Cena)'), ('excursion', 'ExcursiÃ³n / Tour'), ('libre', 'Tiempo libre'), ('otro', 'Otra actividad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
