# Generated by Django 4.2.30 on 2026-06-28 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agencias', '0001_initial'),
        ('viajes', '0003_hotel_grupo_documentorequerido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='DNI', max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='agencias.agencia')),
                ('grupos', models.ManyToManyField(blank=True, related_name='alumnos', to='viajes.grupo')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddConstraint(
            model_name='alumno',
            constraint=models.UniqueConstraint(fields=('agencia', 'numero_documento'), name='unique_documento_por_agencia'),
        ),
    ]
