# Generated by Django 4.2.30 on 2026-06-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_etapaitinerario_codigo_etapaitinerario_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='colegio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='viaje',
            name='grado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='viaje',
            name='nivel_educativo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
