# Generated by Django 4.2.30 on 2026-06-28 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('agencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Dirección de email — usada como login. Única en todo el sistema.', max_length=254, unique=True, verbose_name='Email')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('padre', 'Padre / Tutor'), ('alumno', 'Alumno'), ('agente', 'Agente de viajes'), ('mecenas', 'Mecenas')], help_text='Determina el portal al que accede y sus permisos en el sistema.', max_length=20, verbose_name='Rol')),
                ('email_verificado', models.BooleanField(default=False, help_text='Invariante #8: el login queda bloqueado hasta que este campo sea True. Se activa mediante el enlace de verificación enviado al registrarse.', verbose_name='Email verificado')),
                ('activo', models.BooleanField(default=True, help_text='Cuenta activa. Desactivar para suspender acceso sin eliminar el registro.', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite acceso al sitio de administración Django.', verbose_name='Es staff')),
                ('ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('agencia', models.ForeignKey(blank=True, help_text='Agencia a la que pertenece el usuario. Obligatoria para agentes. Nullable para padres, alumnos y mecenas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='agencias.agencia', verbose_name='Agencia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'indexes': [models.Index(fields=['agencia', 'rol'], name='usuario_agencia_rol_idx'), models.Index(fields=['email'], name='usuario_email_idx')],
            },
        ),
    ]
