# Generated by Django 4.2.30 on 2026-06-28 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadreTutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, help_text='Documento de identidad del tutor.', max_length=20, verbose_name='DNI')),
                ('relacion_alumno', models.CharField(blank=True, choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor_legal', 'Tutor legal')], help_text='Vínculo del tutor con el alumno: padre, madre o tutor legal. Puede completarse en el wizard de inscripción (D-09).', max_length=20, verbose_name='Relación con el alumno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.OneToOneField(help_text="Cuenta de usuario asociada. Solo debe usarse con rol='padre'.", on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Padre / Tutor',
                'verbose_name_plural': 'Padres / Tutores',
            },
        ),
    ]
